### ISSUE TITLE
[1.17.1] JEI Item Search not working

### ISSUE THREAD

**Issue by sky-is-winning** [r8420/MoreOverlays-updated#17]
JEI 1.17.1-8.0.0.14
More Overlays 1.19.2-mc1.17.1

This is on a vanilla server, but I was under the belief this was meant to work client side.

I'm typing part of an item name (let's say Iron) into JEI's search bar, double clicking annnd, nothing

Chunk Boundaries and Light Level overlays work fine.

I've tried removing my resource pack too since it edits the inventory GUI, no effect

**Comment by r8420** [comment]
Correct, I released 1.19.2 before JEI for 1.17.1 was released so that's why the the search functionality is not implemented yet. The next version of More Overlays for 1.17 will have a working JEI item search.

**Comment by r8420** [comment]
Just released version 1.19.3 and it should work again
