### ISSUE TITLE
[Feature Request] Config option to disable JEI Search Item Highlight feature

### ISSUE THREAD

**Issue by BlueAmulet** [r8420/MoreOverlays-updated#18]
Me and a few of my friends are having issues where when using JEI the search feature keeps unintentionally enabling itself and it would be nice if there was an option to disable the search feature entirely.

**Comment by r8420** [comment]
Good idea. I'll implement it in the next few weeks. For now you'll have to double click the search bar to disable the search.

**Comment by r8420** [comment]
I added a toggle to disable the JEI search in the latest version.
