### ISSUE TITLE
Visual item glitch when overlays are on

### ISSUE THREAD

**Issue by EvergreenSystems** [r8420/MoreOverlays-updated#22]
Mod version 1.20.4-1.18
Forge 39.0.5

When light and/or chunk boundary overlays are turned on, the item held in both hands passes through surrounding blocks when the player is near, and an odd texture glitch occurs where certain "bits" are displaced. Not critical by any means, just a rather odd visual bug that I have no clear explanation for.
![2021-12-24_10 37 36](https://user-images.githubusercontent.com/23658767/147365018-db9eaeeb-1d0d-42da-9d8f-5fdeba8b6d56.png)
![2021-12-24_10 37 47](https://user-images.githubusercontent.com/23658767/147365020-80fd8670-3ccd-4be6-b243-3fb01ba45501.png)
![2021-12-24_10 38 11](https://user-images.githubusercontent.com/23658767/147365024-a4564d4a-dfd9-4fa6-9fa6-0e088f5d5cb5.png)
![2021-12-24_10 37 58](https://user-images.githubusercontent.com/23658767/147365026-24c9b233-091c-4cd6-8615-80d3828345cd.png)

**Comment by r8420** [comment]
Fixed in [1.18.1] MoreOverlays 1.20.5
