### ISSUE TITLE
[1.18.2] Crash on world load with JEI 9.7.0.209

### ISSUE THREAD

**Issue by Aerospacesmith** [r8420/MoreOverlays-updated#30]
https://pastebin.com/f0EuUvyV

<details>
  <summary>Crash excerpt</summary>
  
  ```
Description: Unexpected error

java.lang.NoClassDefFoundError: mezz/jei/common/gui/overlay/IngredientListOverlay
	at at.ridgo8.moreoverlays.itemsearch.JeiModule.updateModule(JeiModule.java:30) ~[moreoverlays-1.20.6-mc1.18.2.jar%23311!/:1.20.6-mc1.18.2] {re:classloading}
	at at.ridgo8.moreoverlays.itemsearch.GuiHandler.onGuiInit(GuiHandler.java:30) ~[moreoverlays-1.20.6-mc1.18.2.jar%23311!/:1.20.6-mc1.18.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_3297_GuiHandler_onGuiInit_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
  ```
</details>

Minecraft 1.18.2
Forge 1.18.2-40.1.54
More Overlays Updated 1.20.6-1.18.2
JEI 9.7.0.209
several other mods

**Comment by Sakatsuky** [comment]
i don't insta crash, but when i open the inventory it crashes, i'm using the 1.20.5 version and so far everything is working fine

**Comment by isaaclepes** [comment]
I am experiencing this issue, also.
MOU: 1.20.6
Forge 1.18.2-40.1.54.
JEI: jei-1.18.2-9.7.0.196

https://gist.github.com/isaaclepes/833c53d035dc7e975c914b5b8b631281

**Comment by isaaclepes** [comment]
Tested JEI 9.7.0.209 and issue persisted
Saw similar issues reported but different errors in #27 

Downgrading to MOU to 1.20.5 and JEI to 1.18.2-9.7.196 has solved the issue for me.

**Comment by Aerospacesmith** [comment]
Upgrading to JEI 10.1.0.202 works, but some other mods aren't compatible with the new JEI API yet

**Comment by isaaclepes** [comment]
Just a note:  JEI 10.1.0.202 and MOU 1.20.6 cause an issue where I am kicked for spamming during the 'joining world' phase of world load.  Sticking with MOU 1.20.5/ JEI 10.1.0.196 for now.

**Comment by ProsperCraft** [comment]
Same issue after connecting to a multiplayer server, the client drops to desktop instantly after connecting.

https://gist.githubusercontent.com/ProsperCraft/531ebe0c6027cff15b2c089677ea88e8/raw/f2a200b45c88fc6a95d106bc4b41344c73e41bec/gistfile1.txt

Had to switch back to lightlevelverlays, I really want this one for TownCraft please fix.

**Comment by Jayryn** [comment]
> Upgrading to JEI 10.1.0.202 works, but some other mods aren't compatible with the new JEI API yet

JEI doesn't support anything under 10.1.0.198 (1.18.2) for gradle mod dependencies anymore

-> you could only add the jar yourself for temporary version fixes

It is unlikely that anything below 10.1.0.198 will be supported in the future

**Comment by Jayryn** [comment]
Scrap the part above -> I'll open a PR for JEI 9 Support of 1.18 in the next days

**Comment by r8420** [comment]
I've released 2 versions that hopefully fixes this issue:
- MoreOverlays 1.20.8 (Alpha): for JEI 10.1.0.228 or higher
- MoreOverlays 1.20.7: for JEI 9.7.0.229 or higher (but not JEI 10)
