### ISSUE TITLE
toggles graphics settings together with Optifine

### ISSUE THREAD

**Issue by GIKExe** [r8420/MoreOverlays-updated#34]
when I press the F7 key or another corresponding button to display the light level, the "camera shake" setting is turned off.

moreoverlays-1.18.15-mc1.16.5

**Comment by Jayryn** [comment]
> when I press the F7 key or another corresponding button to display the light level, the "camera shake" setting is turned off.
> 
> moreoverlays-1.18.15-mc1.16.5

Issue is easily fixed with changes made in your minecraft controls -> either change F7 Key by MoreOverlays-Updated or the Camera Shake

Changing the default Hotkey for this is not ideal and won't likely be changed

**Comment by r8420** [comment]
You're not using the latest version for 1.16.5.
The latest version of More Overlays Updated is [[1.16.5] MoreOverlays 1.18.18](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3639017)
