### ISSUE TITLE
Incompatibility with InventoryProfilesNext concerning Visual Glitches

### ISSUE THREAD

**Issue by Jayryn** [r8420/MoreOverlays-updated#40]
**I've noticed that the item amount flickering in 1.19, when searching for items, still exists.**
This Issue should be fixed with Commit 2236dd5, but doesn't seem to be fixed.
(Couldn't test it earlier)

**Version:** `1.21.3 (directly build from latest commits)`

**Issue Explanation Video**
[Preview of 1.19 Amount Issue](https://user-images.githubusercontent.com/77808206/183471617-b1e19dd6-8045-4552-a4a9-edc37da76071.mp4) [Video]

**How it should look**
[Preview of working 1.18](https://user-images.githubusercontent.com/77808206/183471644-48782c40-b8a9-4786-8e59-c0ddf235598e.mp4) [Video]

**Comment by r8420** [comment]
Oh that's weird. I thought you meant something else. I'm not able to replicate this.
Versions I'm using:
moreoverlays-1.21.3-mc1.19.jar, 
jei-1.19.1-forge-11.2.0.244.jar
Forge 42.0.9 on 1.19.1

**Comment by r8420** [comment]
@drjayy 
I'm also unable to replicate it on:
moreoverlays-1.21.3-mc1.19.jar,
jei-1.19-forge-11.1.1.239.jar
Forge 41.0.98 for 1.19

**Comment by Jayryn** [comment]
> Oh that's weird. I thought you meant something else. I'm not able to replicate this.
> Versions I'm using:
> moreoverlays-1.21.3-mc1.19.jar, 
> jei-1.19.1-forge-11.2.0.244.jar
> Forge 42.0.9 on 1.19.1

I'll check my version numbers later and look if my issue still persists in a closed environment. Thanks for helping though

**Comment by Jayryn** [comment]
This may be related to some kind of Minecraft setting or texture pack aswell

-> will test this later on

**Comment by Jayryn** [comment]
I can't reproduce this issue on Forge 1.19.2 anymore (also quarantined every other mod -> likely interference)

This is likely a compatibility issue with another mod, I have an idea which one but I'll try it out in a second in quarantine containers.

**EDIT:** @r8420 This is a compatibility issue with [InventoryProfilesNext](https://github.com/blackd/Inventory-Profiles), I am unsure what causes this, but there may be a workaround, if you'd like to support this incompatibility.

**Comment by Jayryn** [comment]
I've noticed that there is an issue with Item Amount Visual Glitches when using both [InventoryProfilesNext](https://github.com/blackd/Inventory-Profiles) and MoreOverlays-Updatedwhen using the search item container function for JEI Search by MoreOverlays. 

InventoryProfilesNext [[CURSEFORGE]](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next) is a widely known inventory addition / sorting Mod for many Users. I believe that most would consider using both simultaneously, but then the explained issue above appears to be happening.

**As I believe many users to want to use both mods simultaneously, I hope that this issue will not be marked as "will not fix".**
[Please let me know if you agree too.]


I've informed the Author of InventoryProfilesNext concerning this issue. [Link to Issue](https://github.com/blackd/Inventory-Profiles/issues/167)

**Comment by r8420** [comment]
I see, when setting highlight_clicking_slot to false in the InventoryProfilesNext config the issue doesn't occur.
![image](https://user-images.githubusercontent.com/26418513/183523142-2d2e687d-865d-4c2e-b3fb-34d05070f571.png)

**Comment by Jayryn** [comment]
> I see, when setting highlight_clicking_slot to false in the InventoryProfilesNext config the issue doesn't occur.
> ![image](https://user-images.githubusercontent.com/26418513/183523142-2d2e687d-865d-4c2e-b3fb-34d05070f571.png)
> 

Thanks, I'll try to reproduce.

**Comment by Jayryn** [comment]
> I see, when setting highlight_clicking_slot to false in the InventoryProfilesNext config the issue doesn't occur.
> ![image](https://user-images.githubusercontent.com/26418513/183523142-2d2e687d-865d-4c2e-b3fb-34d05070f571.png)
> 

Where exactly did you find this setting, I can't seem to locate it

**EDIT:** Ignore this, I'm just blind

**Comment by Jayryn** [comment]
Thank you, this fixed the issue :)
