### ISSUE TITLE
[1.19.2] Jei 11.5.0 and up crash on world join

### ISSUE THREAD

**Issue by YOYOK9** [r8420/MoreOverlays-updated#47]
Jei versions 11.5.0.x and up crash with MoreOverlays in 1.19.2 when connecting to a world. 

Tested with: 
Forge: 43.2.2
moreoverlays-1.21.3-mc1.19
jei-1.19.2-forge-11.4.0.290 - No crash
jei-1.19.2-forge-11.5.0.291 - Crash

Latest.log: https://gist.github.com/YOYOK9/00393c50bd8ee0f817405c23c5089f67
Debug.Log: https://gist.github.com/YOYOK9/b5dc1b1d30381aa0d0bf3f34af718fe8

Steps to reproduce:
1) Add JEI 11.5.0.x+ and MoreOverlays
2) Try to create/join a SP world

Extra notes:
I also tested this with jei-1.19.2-forge-11.5.0.297
latest.log: https://gist.github.com/YOYOK9/b906e6c846e91312ab275046235db938

**Comment by DrSigma4164** [comment]
Same problem as you. I can confirm this incompatibility issue

**Comment by r8420** [comment]
Can confirm. JEI made some changes that break More Overlays. I'll try to fix it in the next few days. For now you'll have to use an older version of JEI.

**Comment by r8420** [comment]
Currently having some trouble using the JEI integration for 11.5.0 so I've created an issue on their repo.
https://github.com/mezz/JustEnoughItems/issues/3093

**Comment by r8420** [comment]
I've released a version that should fix this issue: [here](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/4322445)
It should be available once it gets accepted on Curseforge.
Please let me know if you encounter any problems with this new version.
