### ISSUE TITLE
Issue with the OpenCubicChunks

### ISSUE THREAD

**Issue by Darius-Beldi** [r8420/MoreOverlays-updated#5]
When i enter the 3rd type of overlay, hunger dissapears and when i enter the Nether Portal the animations are canceled. Those bugs dont occur while OpenCubicChunks is hidden. [Here is a video](https://youtu.be/s0SyOYLt-TE)

**Comment by r8420** [comment]
Thanks for reporting the issue. This will be fixed in the next release of the mod.

**Comment by r8420** [comment]
It should be fixed in version 1.18.10: https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3099374
