### ISSUE TITLE
Crash on launch.

### ISSUE THREAD

**Issue by HypersonicMarshmallow** [r8420/MoreOverlays-updated#54]
[crash-2023-02-16_10.07.55-fml.txt](https://github.com/r8420/MoreOverlays-updated/files/10757969/crash-2023-02-16_10.07.55-fml.txt)
This mod requires a lower version of JEI than I have, and lowering it to that version causes JEI to be incompatible with the rest of the pack.
The pack, for reference: https://beta.curseforge.com/minecraft/modpacks/chaotic-flock 

my name in the crash report has been replaced with "\<User\>".

**Comment by r8420** [comment]
The moreoverlays version that you were using was version moreoverlays-1.20.9-mc1.18.2, that version only supported JEI 9.
Version 1.20.10 and 1.20.11 have support for the new JEI version 10
