### ISSUE TITLE
Modpack crash connected to mandatory jei version

### ISSUE THREAD

**Issue by xFirefalconx** [r8420/MoreOverlays-updated#55]
![grafik](https://user-images.githubusercontent.com/106652912/220988445-11cb6ee8-695e-48ae-b3fb-159ceffd906e.png)
Modpack creator here. I'm using a mod that relies on the latest jei version. I cannot launch the game as is. Is there a reason why the version has to be lower than the latest?
[latest.log](https://github.com/r8420/MoreOverlays-updated/files/10816673/latest.log)
[crash-2023-02-23_17.47.20-fml.txt](https://github.com/r8420/MoreOverlays-updated/files/10816674/crash-2023-02-23_17.47.20-fml.txt)

**Comment by xFirefalconx** [comment]
Update, it's actually working for the Beta. Cluster crash on Release is not so funny. 
Either way, see here for more info: https://github.com/immortius/chunkbychunk/issues/59

**Comment by r8420** [comment]
Sorry about that, it was not very clear there were 2 separate versions one for JEI 9 and one for JEI 10. 
I've just released a new version for 1.18.2 which support both JEI 9 and 10. It will be available once approved by Curseforge.
