### ISSUE TITLE
Feature request: Light Overlay status (on/off) somewhere

### ISSUE THREAD

**Issue by n21lv** [r8420/MoreOverlays-updated#56]
Using **moreoverlays-1.21.5-mc1.19.2.jar**.

When you have an area lit up, it's quite difficult to understand whether the overlay is enabled or not. Something like a status message in the debug screen would be a minor, but a very welcome enhancement :)

**Comment by r8420** [comment]
Thank you for the feature request [n21lv](https://github.com/n21lv),
I've submitted 2 new versions to CurseForge with a new status message that will show up for a few seconds when changing the overlay mode. The versions should be available once accepted by CurseForge.
![image](https://github.com/r8420/MoreOverlays-updated/assets/26418513/f24cd6b0-d326-417c-9fb0-2e4415d630e4)
