### ISSUE TITLE
more search functionality 

### ISSUE THREAD

**Issue by xXseesXx** [r8420/MoreOverlays-updated#59]
please also add in search for tooltip i dont want to check every firmalife bee i stored for the one that has 10/10 stats

**Comment by r8420** [comment]
Sure

**Comment by r8420** [comment]
I've release a new version for Forge 1.18.2, 1.19.2 and 1.20~1.20.2 that has this new feature. It is enabled by default and can be disabled in the config. I will also include it in future releases.
edit: also released it for 1.16.5
