### ISSUE TITLE
Modrinth release?

### ISSUE THREAD

**Issue by lonevox** [r8420/MoreOverlays-updated#63]
Could this be uploaded to Modrinth? It is one of the only mods in my pack that isn't on Modrinth so an upload there would be awesome! If a Modrinth release isn't planned, is it okay to distribute your jars in my pack (the notice at the bottom of the curseforge page suggests that I can, but just clarifying)?

**Comment by r8420** [comment]
Please check https://modrinth.com/mod/more-overlays-updated

**Comment by lonevox** [comment]
I don't know how I missed that! Thanks :)

**Comment by MosquitoCoding** [comment]
Hey, I just found the newest version of this mod on Curseforge by accident. Usually I only use Modrinth and there its outdated. Just an info✌🏼
