### ISSUE TITLE
Lags with Chisels and Bits

### ISSUE THREAD

**Issue by MelanX** [r8420/MoreOverlays-updated#9]
If you run 1.16.3 or 1.16.4 with Chisels and Bits and MoreOverlays and press F7 it laggs a lot if you’re looking at a building made with CaB. 
If you need any versions, latest should still have the problem. 
I think it happens because MoreOverlays tries to render a cross on each block but a chisels and Bits block has 256 blocks instead of just one, but I'm not sure.

**Comment by r8420** [comment]
Can you try the newest version? https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated/files/3172013

**Comment by MelanX** [comment]
Oh, sorry! I never got a notification for that, or I missed it!
